### ISSUE TITLE
Do not commit generated .class files

### ISSUE THREAD

**Issue by Shetza** [J-H-Schwartz/Donjons_Dragons#1]
bin/main

**Comment by J-H-Schwartz** [comment]
Added bin directory to .gitignore, see commit https://github.com/J-H-Schwartz/Donjons_Dragons/commit/aae78cd1e1434bbbd9cfc80ab248301c24370794 , and deleted bin directory from git rep, see commit https://github.com/J-H-Schwartz/Donjons_Dragons/commit/a8df0bf651a487a54e024a9c84d41768142abeb0
