### ISSUE TITLE
Do not use static unless for main

### ISSUE THREAD

**Issue by Shetza** [J-H-Schwartz/Donjons_Dragons#3]
DonjonsAndDragons class may create a new instance of MainMenu (which mus be public) and class a public "start" method.
Every attributes must be private and non-static !

**Comment by J-H-Schwartz** [comment]
Changed remaining static methods and vars to non static. See commit  https://github.com/J-H-Schwartz/Donjons_Dragons/commit/aae78cd1e1434bbbd9cfc80ab248301c24370794
